# Generated by Django 3.2 on 2021-04-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210414_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(to='api.Horario'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico', unique_for_date='dia'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(),
        ),
    ]
