# Generated by Django 3.2 on 2021-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia']},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(),
        ),
    ]
