# Generated by Django 3.2 on 2021-04-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210417_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.agenda'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(unique=True),
        ),
    ]
