# Generated by Django 3.2 on 2021-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_consulta_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.BigIntegerField(),
        ),
    ]
