# Generated by Django 3.2 on 2021-04-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['dia', 'horario']},
        ),
    ]
