# Generated by Django 3.2 on 2021-04-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210419_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['agenda', 'horario']},
        ),
    ]
